# Generated by Django 5.0.4 on 2024-04-16 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arababack', '0002_charging'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('content', models.TextField()),
            ],
        ),
    ]
