# Generated by Django 5.0.4 on 2024-04-22 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arababack', '0003_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Accessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('car', models.ForeignKey(default='Universal', on_delete=django.db.models.deletion.CASCADE, to='arababack.car')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arababack.manufacturer')),
            ],
        ),
    ]
